inkscape product_eval.svg -E product_eval.eps
inkscape product_translate_amazon_with_none.svg -E product_translate_amazon_with_none.eps
inkscape product_translate_amazon_without_none.svg -E product_translate_amazon_without_none.eps
inkscape product_feature_selection_with_none.svg -E product_feature_selection_with_none.eps
inkscape product_feature_selection_without_none.svg -E product_feature_selection_without_none.eps
inkscape sampling_optimization.svg -E sampling_optimization.eps
