gnuplot_args=-e "fontname='Verdana'; fontsize='14'"

run:
	cd sampling_optimization && gnuplot $(gnuplot_args) -p *.plt
	cd product_evaluation && gnuplot $(gnuplot_args) -p *.plt
	cd product_feature_selection && gnuplot $(gnuplot_args) -p *.plt
